name: "Install Template Project"
description: "Installs dependencies and sets up the Template project environment."
inputs:
  ssh_private_key:
    description: "SSH Private Key for accessing private repositories"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    # Step 0: check code
    - name: CheckOut code
      shell: bash
      uses: actions/checkout@v3
      with:
        repository: yoofa/yf-actions
        ref: main  # or the specific branch/tag you want
    
    # Step 1: 设置 SSH（如果提供了 SSH_PRIVATE_KEY）
    - name: Set up SSH
      shell: bash
      if: ${{ inputs.ssh_private_key != '' }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Step 2: 缓存 depot_tools
    - name: Cache depot_tools
      uses: actions/cache@v3
      with:
        path: $HOME/depot_tools
        key: ${{ runner.os }}-depot_tools-${{ hashFiles('base-test-build-action/install-deps.sh') }}
        restore-keys: |
          ${{ runner.os }}-depot_tools-

    # Step 3: 安装依赖
    - name: Install dependencies
      shell: bash
      run: |
        ls
        chmod +x base-test-build-action/install-deps.sh
        ./base-test-build-action/install-deps.sh

    # Step 4: 将 depot_tools 添加到 PATH
    - name: Add depot_tools to PATH
      shell: bash
      run: echo "$HOME/depot_tools" >> $GITHUB_PATH

    # Step 5: 设置 .gclient 文件
    - name: Setup .gclient File
      shell: bash
      run: |
        mkdir -p code
        cp ./.gclient code/.gclient

    # Step 6: 运行 gclient sync 下载代码
    - name: Run gclient sync
      shell: bash
      run: |
        cd code
        gclient sync
